### ISSUE TITLE
프롬프트 프로토타입 제작

### ISSUE THREAD

**Issue by arako** [TaeKyuHyeon/btd-front#7]
- [x] 텍스트인풋
- [x] 버튼
- [x] api 연결 및 에러처리
- [x] POST api 전송
- [x] 이미지 노출

**Comment by arako** [comment]
## codepen notepad reference

- https://codepen.io/mdeken/pen/YVzxJv
- https://codepen.io/labnol/pen/DEKNgE
- https://codepen.io/soulchainer/pen/oBZJQM
- https://codepen.io/soulchainer/pen/oBZJQM
- https://codepen.io/mdeken/pen/YVzxJv

**Comment by arako** [comment]
### API Swagger
http://152.67.222.127:3000/api-docs/#/default/get_example

**Comment by arako** [comment]
@tkbro 
1. API 호출시 cors 에러 발생
    - localhost / https://taekyuhyeon.github.io 페이지 예외처리 필요
    - https 설정도 되어있나?
2. ~정상 호출 테스트를 위한 프롬프트 명령어 예제~

**Comment by tkbro** [comment]
> @tkbro
> 
> 1. API 호출시 cors 에러 발생
>    
>    * localhost / https://taekyuhyeon.github.io 페이지 예외처리 필요
>    * https 설정도 되어있나?
> 2. ~정상 호출 테스트를 위한 프롬프트 명령어 예제~

https://github.com/TaeKyuHyeon/backtodiary/pull/11 pr 로 처리되었습니다
https 는 미적용 입니다
